---
title: "ggplot1"
author: "Xintao Ding"
date: "9/26/2019"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df

```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + geom_point(aes(color = name), alpha = .4) + geom_smooth(se = FALSE) + facet_grid(. ~ name)  # creating plot and printing at the same point
```


```{r}
scatterplot = weather_df %>% 
  ggplot(aes(x= tmin, y = tmax)) + geom_point()
```

why do positions of color matter? The first aes define everything, if color placed in the first aes(), every layers will be in that color

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + geom_point(alpha = .4) +geom_smooth(se = FALSE) + facet_grid(. ~ name)
```

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5)+
  geom_smooth(size = .5, se = FALSE)
```

## 2d density
```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
```

```{r}
ggplot(weather_df, aes(x = tmax)) + 
  geom_histogram()
```

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2) # for historgram, color is the out color, while fill is inside the bar color
```
```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4, adjust = .5, color = "blue")
```

```{r}
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin), color = "blue")
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin, color = "blue")) 

#In the first attempt, we’re defining the color of the points by hand; In the second attempt, we’re implicitly creating a color variable that has the value blue everywhere; ggplot is then assigning colors according to this variable using the default color scheme.


```

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + geom_boxplot()
```

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  stat_summary(fun.y = median, geom = "point", color = "blue", size = 4)
```

```{r}
ggplot_rid = 
  ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)


ggsave("ggplot_temp_ridge.pdf", ggplot_rid)  # safe to name the plot and then save
```
```{r fig.width = 6}
```

## Figure Width
```{r fig.width = 6}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5)+
  geom_smooth(size = .5, se = FALSE)
```
```{r fig.width= 12}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5)+
  geom_smooth(size = .5, se = FALSE)
```

